---
title: CMSC508 - Project Deliverable 4 - ER Diagrams
author: Brian Montecino, Corbin Nash
date: 10-14-2023
format:
    html:
        toc: true
        embed-resources: true
---
# chen diagram of 
```{dot}

graph ER {
    layout=neato;
    node [shape=box]; User, Budget, Actuals, Transaction
    node [shape=ellipse]; userID, budgetID, expectedExpense, expectedIncome, difference, transactionID, realExpense, realIncome, comparison, source
    node [shape=diamond,style=filled,color=lightgrey]; manages, compares_to, consists_of, creates

    User -- creates [label = "1",len=1.3]
    User -- manages [label = "1"]    
    Budget -- manages [label = "n",len=1.2]
    Budget -- compares_to [label = "1",len=1]
    Actuals -- compares_to [label = "1"]
    Actuals -- consists_of [label = "1"]
    Transaction -- consists_of [label = "n",len=1.4]
    Transaction -- creates [label = "n"]

    User -- userID

    Budget -- budgetID
    Budget -- expectedExpense [len=1.1]
    Budget -- expectedIncome [len=1.3]


    Actuals -- realExpense
    Actuals -- realIncome[len=1.3]
    Actuals -- comparison

    Transaction -- source
    Transaction -- transactionID [len = 1.5]
    Transaction -- difference
}